<robot name="camera" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="camera_x" value="0.05" />
    <xacro:property name="camera_y" value="0.05" />
    <xacro:property name="camera_z" value="0.05" />
    <xacro:property name="camera_m" value="0.1" />
    <link name="camera">
        <visual>
            <geometry>
                <box size="${camera_x} ${camera_y} ${camera_z}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="green">
                <color rgba="1 0.756862 0.756862 0.5" />
            </material>
        </visual>

        <!-- 碰撞参数 -->
        <collision>
            <geometry>
                <box size="${camera_x} ${camera_y} ${camera_z}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <!-- 惯性参数 -->
        <xacro:box_inertial_matrix m="${camera_m}" l="${camera_x}" w=" ${camera_y}" h="${camera_z}" />
    </link>

    <joint  name = "cam2car_base" type="continuous">
        <parent link="car_base" />
        <child link="camera" />
        <origin xyz="${car_base_x/2-camera_x/2}  0 ${car_base_z/2+camera_z/2}" />
    </joint>

    <gazebo reference="camera">
        <material>Gazebo/Black</material>
    </gazebo>
</robot>