<robot name="car_base" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="car_base_x" value="0.6" />
    <xacro:property name="car_base_y" value="0.4" />
    <xacro:property name="car_base_z" value="0.2" />
    <xacro:property name="base_link_m" value="0.5" />
    <xacro:property name="wheel_radius" value="0.0625" />
    <link name="basefootprint">
        <visual>
            <geometry>
                <sphere radius="0.00001" />
            </geometry>
        </visual>
    </link>

    <link name="car_base">
        <visual>
            <geometry>
                <box size="${car_base_x} ${car_base_y} ${car_base_z}" />
            </geometry>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <material name="green">
                <color rgba="1 0.756862 0.756862 0.5" />
            </material>
        </visual>

        <!-- 碰撞参数 -->
        <collision>
            <geometry>
                <box size="${car_base_x} ${car_base_y} ${car_base_z}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <!-- 惯性参数 -->
        <xacro:box_inertial_matrix m="${base_link_m}" l="${car_base_x}" w="${car_base_y}" h="${car_base_z}" />

    </link>


    <joint name="base_footprint2car_base" type="fixed">
        <parent link="basefootprint" />
        <child link="car_base" />
        <origin xyz="0 0 ${car_base_z/2+wheel_radius}" rpy="0 0 0"/>
    </joint>
    <gazebo reference="car_base">
        <material>Gazebo/Yellow</material>
    </gazebo>

</robot>