<robot name="my_laser" xmlns:xacro="http://wiki.ros.org/xacro">
    <xacro:property name="laser_length" value="0.05" /> <!-- 雷达长度 -->
    <xacro:property name="laser_radius" value="0.03" /> <!-- 雷达半径 -->
    <xacro:property name="laser_m" value="0.1" /> <!-- 雷达质量 -->

    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="black">
                <color rgba="0 0 0 0" />
            </material >
        </visual>


        <collision>
            <geometry>
                <cylinder radius="${laser_radius}" length="${laser_length}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>

        <xacro:cylinder_inertial_matrix m="${laser_m}" r="${laser_radius}" h="${laser_length}" />
    
    </link>

    <joint name="laser2support" type="fixed">
        <parent link="car_base" />
        <child link="laser" />
        <origin xyz="0.0 0.0 ${laser_length / 2+0.15}" />
    </joint>
    
    <gazebo reference="laser">
        <material>Gazebo/Black</material>
    </gazebo>
</robot>
