<robot name="ladar" xmlns:xacro="http://www.ros.org/wiki/xacro">
    <xacro:property name="ladar_radius" value="0.1" />
    <xacro:property name="ladar_height" value="0.1" />
    <xacro:property name="ladar_m" value="0.1" />

    <link name="laser">
        <visual>
            <geometry>
                <cylinder radius="${ladar_radius}" length="${ladar_height}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="black">
                <color rgba="0 0 0 0" />
            </material >
        </visual>

        <!-- 碰撞参数 -->
        <collision>
            <geometry>
                <cylinder radius="${ladar_radius}" length="${ladar_height}" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </collision>
        <!-- 惯性参数 -->
        <xacro:cylinder_inertial_matrix m = "${ladar_m}" r = "${ladar_radius}" h="${ladar_height}" />

    </link>

    <joint  name = "laser2car_base" type="fixed">
        <parent link="car_base" />
        <child link="laser" />
        <origin xyz="0  0 ${car_base_z/2+ladar_height/2}" />
    </joint>

    <gazebo reference="laser">
        <material>Gazebo/Black</material>
    </gazebo>
</robot>